### ISSUE TITLE
Undirected acyclicity constraint bevahiour

### ISSUE THREAD

**Issue by acairncross** [sambayless/monosat#21]
It seems that having any undirected edges in a graph causes it to be cyclic. Is this the intended behaviour/is there another way to express the acyclicity constraint that I want?

```py
>>> from monosat import *
>>> g = Graph()
>>> n1, n2 = [g.addNode() for _ in range(2)]
>>> e1 = g.addUndirectedEdge(n1, n2)
>>> Assert(g.acyclic(directed=False))
>>> Assert(e1)
>>> Solve()
False
```

**Comment by sambayless** [comment]
I should improve the documentation about undirected acyclicity. Since under
the covers monosat only supports directed edges right now, the undirected
acyclicity predicate was implemented somewhat awkwardly.

For the purposes of the undirected acyclicity predicate (and only for that
predicate), directed edges are treated as undirected.

Because normally undirected edges are implemented by adding two directed
edges in opposite directions, those faux "undirected edges" immediately
introduce an undirected cycle, as far as the undirected acyclicity
predicate is concerned.

So instead, you should introduce only a single directed edge between each
node (in an arbitrary direction). The acyclicity predicate will treat that
edge as if it were undirected, and enforce acyclicity over that graph.

**Comment by acairncross** [comment]
Ah thanks, that works :+1:
