### ISSUE TITLE
Build only statically/dynamically linked libraries and binaries?

### ISSUE THREAD

**Issue by acairncross** [sambayless/monosat#23]
From what I understand, the build for monosat builds both dynamically linked libraries/binaries and statically linked libraries/binaries. Is there a way to only build one or the other (dynamic or static)?

**Comment by sambayless** [comment]
I originally intended to set it up so that you could build only one or the
other, but right now I believe it only ever builds both (and I'd like to
keep the current default behavior).

It shouldn't be too hard to alter the cmake build file to add something
like a "build-static", "build-dynamic" options, which would cut the build
time in roughly half if you only wanted one or the other.
